Implement Backpropagation algorithm to train an ANN of configuration 3x2x2x1 to achieve majority function with 3-bit data. Output of the network must be 1 when there are two or more 1’s in the data.

In [3]:
import numpy as np

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sder(x):
    return x * (1 - x)

X = np.array([[0,0,0],[0,0,1],[0,1,0],[0,1,1],[1,0,0],[1,0,1],[1,1,0],[1,1,1]])
Y = np.array([[0],[0],[0],[1],[0],[1],[1],[1]])

inp = 3
hid1 = 2
hid2 = 2
out = 1
lr = 0.1

# Initialize the weights and biases of each layer
W1 = np.random.uniform(size=(hid1, inp))
b1 = np.random.uniform(size=(hid1, 1))
W2 = np.random.uniform(size=(hid2, hid1))
b2 = np.random.uniform(size=(hid2, 1))
W3 = np.random.uniform(size=(out, hid2))
b3 = np.random.uniform(size=(out, 1))

epoch = 10000
for i in range(epoch):
    index = np.random.randint(len(X))
    x = X[index].reshape(-1,1)
    y = Y[index].reshape(-1,1)

    # Forward propagation
    a1 = sigmoid(np.dot(W1, x) + b1)
    a2 = sigmoid(np.dot(W2, a1) + b2)
    a3 = sigmoid(np.dot(W3, a2) + b3)

    # Backward propagation
    error = y - a3
    del3 = error * sder(a3)
    del2 = np.dot(W3.T, del3) * sder(a2)
    del1 = np.dot(W2.T, del2) * sder(a1)

    # Update weights and biases
    W3 += lr * np.dot(del3, a2.T)
    b3 += lr * del3
    W2 += lr * np.dot(del2, a1.T)
    b2 += lr * del2
    W1 += lr * np.dot(del1, x.T)
    b1 += lr * del1

    if (i+1) % 1000 == 0:
      error = np.mean(np.abs(error))
      print("Iteration: {}, W1: {}, b1: {}, W2: {}, b2: {},W3: {}, b3: {}, Error: {}".format(i+1, W1, b1, W2, b2, W3, b3, error))

# Test the model
for i in range(len(X)):
    x = X[i]
    y = Y[i]
    x = x.reshape(-1, 1)
    y = y.reshape(-1, 1)
    a1 = sigmoid(np.dot(W1, x) + b1)
    a2 = sigmoid(np.dot(W2, a1) + b2)
    a3 = sigmoid(np.dot(W3, a2) + b3)
    print("Input:", x.T, "Output:", y.T, "Predicted Output:", a3.T)



Iteration: 1000, W1: [[0.44133559 0.63168773 0.22489154]
 [0.98009919 0.01502338 0.82075978]], b1: [[0.80085038]
 [0.88033555]], W2: [[0.38599123 0.18113908]
 [0.8381919  0.83856199]], b2: [[0.62475787]
 [0.82256958]],W3: [[0.43751285 0.0136587 ]], b3: [[-0.31090853]], Error: 0.5146787818374324
Iteration: 2000, W1: [[0.45144373 0.64161415 0.23259589]
 [0.98309958 0.01751625 0.82301868]], b1: [[0.78561469]
 [0.8709231 ]], W2: [[0.42214456 0.2213296 ]
 [0.83385196 0.834176  ]], b2: [[0.60433277]
 [0.81551473]],W3: [[0.54902611 0.16367843]], b3: [[-0.25703632]], Error: 0.5827882219434318
Iteration: 3000, W1: [[0.46289252 0.65243608 0.24251477]
 [0.98742439 0.02006336 0.82663754]], b1: [[0.76281572]
 [0.85485436]], W2: [[0.43699754 0.2415518 ]
 [0.82639208 0.82682855]], b2: [[0.5511288 ]
 [0.79957142]],W3: [[0.43567804 0.03950345]], b3: [[-0.5128134]], Error: 0.5451094046847021
Iteration: 4000, W1: [[0.47680233 0.66695723 0.25851488]
 [0.99345582 0.024064   0.83372917]], b1: [[0.73493795]
